export const MAIN = '#f57b51';
export const BLACK = '#1d1d1d';
export const WHITE = '#FFFFFF';
export const LABEL = '#cdcdcd';
export const RED = '#ff0000';
export const TRANSPARENT = 'transparent';
export const SHADOW = 'rgba(183, 183, 183, 0.5)';
export const GRAY = '#767676';
export const BORDER = '#f6f6f6';
